version: '3.8'

services:
  sql_server_container:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server_container 
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!@#
    ports:
      - "14333:1433"
    volumes:
      - ../database:/var/opt/mssql/data 
    restart: always

  nginx_mssql_proxy:
    image: nginx:latest
    container_name: nginx_mssql_proxy
    ports:
      - "14334:1433"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - sql_server_container
    restart: always